apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Backend deploy v2"
  name: back-deploy
  labels:
    app: back
    env: pro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:      
       - name: golang-back
         image: swarthydj/golangbck:v3
---
apiVersion: v1
kind: Service
metadata:
  name: svc-back
  labels:
    app: back
spec:
  type: ClusterIP      
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
